### ISSUE TITLE
Problems with postgres

### ISSUE THREAD

**Issue by davidhq** [3kg4kR/active_record#1]
Hi,

Works with sqlite and mysql but with postgres I get:

```
/Users/david/Projects/booktical/node_modules/active_record/node_modules/any-db/index.js:37
		throw new Error("Unknown database driver: " + name)
		      ^
Error: Unknown database driver: pg
```

Any hints?

thank you

**Comment by 3kg4kR** [comment]
You installed 'pg'?
try: $ npm install pg pg-native


Date: Thu, 12 Mar 2015 16:28:26 -0700

**Comment by davidhq** [comment]
Yes, your package installed it:

```
[sqlite3] Success: "/Users/david/Projects/booktical/node_modules/active_record/node_modules/sqlite3/lib/binding/node-v11-darwin-x64/node_sqlite3.node" is installed via remote
active_record@0.1.4 node_modules/active_record
├── any-db@0.3.5 (any-db-pool@2.1.0)
├── mysql@2.0.0-alpha7 (require-all@0.0.3, bignumber.js@1.0.1)
├── pg@0.12.3 (generic-pool@2.0.2)
└── sqlite3@3.0.5 (nan@1.6.2)
```

I fixed the problem and sent you a pull request...

But now I have a further issue:

```
$ node ar.js 
ActiveRecord::ConnectionNotEstablished: Please establish the connection with database

/Users/david/Projects/booktical/node_modules/active_record/lib/transaction.js:29
			throw ConnectionNotEstablished;
			      ^
ActiveRecord::ConnectionNotEstablished: Please establish the connection with database
```
I have all the databases locally without password, so my config is like this:

```
ActiveRecord.Base.configure_connection({
    driver: 'postgres',
    hostname: 'localhost',
    user: 'david',
    password: '',
    database: 'tb'
});
```
Maybe this is bothering it? I'll try to set a password on one database and see...

**Comment by davidhq** [comment]
I couldn't sleep without trying :) So I did and it doesn't work in any case... with passwords or without... something is definitelly wrong.. can you maybe try? I tried locally on OSX and on the Debian server.

**Comment by 3kg4kR** [comment]
:) I'm trying now!

**Comment by davidhq** [comment]
ok, I tried 'mysql' to actually retrieve stuff on a db with user without password and it works...

the only thing is that node doesn't exit, I have to Ctrl+C it: http://cl.ly/image/330S2u35112P

**Comment by 3kg4kR** [comment]
The connection is open. You need close then...

Try now. I push now the fixies...

**Comment by davidhq** [comment]
I updated another line (#126 in connection.js) as per your last commit..

but still something else fails:

```
ActiveRecord::ConnectionNotEstablished: Error: getaddrinfo ENOTFOUND

/Users/david/Projects/booktical/node_modules/active_record/lib/connection.js:152
						throw ConnectionNotEstablished;
						      ^
ActiveRecord::ConnectionNotEstablished: Error: getaddrinfo ENOTFOUND
```

PS: closing the connection in mysql worked... but I think I didn't need to close for sqlite - this is ok?

**Comment by davidhq** [comment]
ok the problem was your example for postgres, it has "host" instead of "hostname"

"prod": {
    "driver": "postgres",
    "user": "test",
    "password": "test",
    "host": "localhost",
    "database": "mydb"
  }

You have to update the readme...

It *almost* works now but still something is wrong:

```
INFO Database connected. Fri, 13 Mar 2015 11:28:10 GMT
 (2ms) rollback transaction
ActiveRecord::ActiveRecordError: bind message supplies 1 parameters, but prepared statement "" requires 0
[]
INFO Database disconnected. Fri, 13 Mar 2015 11:28:10 GMT
```

the same code works with mysql

Code: https://gist.github.com/davidhq/7414f8bcb168638cd8b7

**Comment by 3kg4kR** [comment]
Solved!

**Comment by davidhq** [comment]
Why reopen? I tried this basic example with pg and it worked...

**Comment by 3kg4kR** [comment]
Try the create, update, destroy methods...

**Comment by davidhq** [comment]
Today or should I wait a few days ? :)

**Comment by 3kg4kR** [comment]
:P

**Comment by 3kg4kR** [comment]
\o/

**Comment by davidhq** [comment]
Hey! So everything should work now? 

How come postgres was supported before? You didn't test it at all until 2 days ago? ;) just interested... 
tnx

**Comment by 3kg4kR** [comment]
Man, if it was not for you I would never do all the tests with the Postgres ... Hahaha

Thank you for helping me. Huge gain of was.

**Comment by 3kg4kR** [comment]
In fact I left the library of 'any-db' this part, have not tested everything.


Again, thank you!

**Comment by davidhq** [comment]
hey no problem! I didn't actually do that much... but you did according to commits.... great, tnx

**Comment by davidhq** [comment]
onemore question - is `ActiveRecord.Base.establish_connection()` synchronous? If not is it possible to pass in a callback that gets called when connection is established?

**Comment by davidhq** [comment]
Also I maybe found another issue, not sure... here: https://gist.github.com/davidhq/801beb3bfbdb3c346976

I want to count backlinks a particular website has... I'm not even there because when setting up models I get this exception....

Is this a bug?

**Comment by 3kg4kR** [comment]
You need create a the model file with name backlink.js, and exports then...

When create a association, I load again this model, and overwrite yours methods(exists, all, last, first).

User.find(1, function (err, user){
    user[0]
    .phones() // return Phone() in `phone.js`
    .first() // return first phone where user_id = user[0].id
    .create({ number: '213133213' }) // return instance of Phone()
})

Each model is a file separated.

**Comment by 3kg4kR** [comment]
New updates man...

**Comment by davidhq** [comment]
After trying your implementation, Waterline and Loopback I decided that for my minimal current use case it's best to just go with https://github.com/brianc/node-postgres .. it work's fine for now, my `database.js` is only 70 lines long.

So in your latest updates it is possible to have many models in the same file?

**Comment by 3kg4kR** [comment]
Ok, man. Thx for your feedback. ;)

I'll think of implementing this...
